[build]
  command = "CI=false npm run build"
  publish = "build"
  timeout = "30m"

[[plugins]]
  package = "@netlify/plugin-cachier"

[build.environment]
  NODE_VERSION = "18.19.0"
  NPM_FLAGS = "--no-audit --no-fund"